name: preparations for updates
description: prepare environment for jobs from `auto-updates` workflow

runs:
    using: composite
    steps:
        - name: Set up nightly Rust
          uses: actions-rs/toolchain@v1
          with:
              profile: minimal
              toolchain: nightly
              components: rust-src, rustfmt, clippy # should be synchronized with `check` workflow
              default: true

        -   name: Install minimal stable
            uses: actions-rs/toolchain@v1
            with:
                profile: minimal
                toolchain: stable


        - name: Set up git user
          run: |
              git config --local user.email "intellij.rust@gmail.com"
              git config --local user.name "intellij-rust-bot"
          shell: bash
