version: 2
updates:
    - package-ecosystem: "cargo"
      directory: "/native-helper"
      schedule:
          interval: "daily"
          time: "04:00" # UTC
      open-pull-requests-limit: 0
      labels: [ ]
      assignees:
          - "vlad20012"

    - package-ecosystem: "gradle"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "04:00" # UTC
      open-pull-requests-limit: 10
      labels: [ ]
      assignees:
          - "Undin"
