[package]
name = "rustc_span"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc_macros = { path = "../rustc_macros" }

[build-dependencies]
reqwest = { version = "0.11.10", features = ["blocking"] }
syn = { version = "1", features = ["full"] }
quote = "1"
