name: auto updates

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * 1' # try each Monday

jobs:
#    update-nightly:
#        runs-on: ubuntu-latest
#        steps:
#            - uses: actions/checkout@v2
#              with:
#                  token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
#
#            - name: Prepare for updates
#              uses: ./.github/actions/preparations-for-updates
#
#            - name: Update nightly
#              run: python scripts/update_nightly.py --token ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

    update-testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

            - name: Prepare for updates
              uses: ./.github/actions/preparations-for-updates

            - name: Update testing
              run: python scripts/update_testing.py --token ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
