name: build plugin

on:
    workflow_dispatch:

jobs:
    generate-build-number:
        runs-on: ubuntu-18.04
        outputs:
            build_number: ${{ steps.buildnumber.outputs.build_number }}
        steps:
            - name: Generate build number
              uses: einaregilsson/build-number@v3
              id: buildnumber
              with:
                  token: ${{ secrets.github_token }}
                  prefix: rust

    build-native-code:
        uses: ./.github/workflows/build-native-code.yml
        with:
            rust-version: stable
            cache: false

    build:
        needs: [ generate-build-number, build-native-code ]
        runs-on: ubuntu-18.04
        strategy:
            fail-fast: true
            matrix:
                platform-version: [ 221, 222 ]
        env:
            ORG_GRADLE_PROJECT_buildNumber: ${{ needs.generate-build-number.outputs.build_number }}
            ORG_GRADLE_PROJECT_platformVersion: ${{ matrix.platform-version }}
            ORG_GRADLE_PROJECT_enableBuildSearchableOptions: true
            ORG_GRADLE_PROJECT_compileNativeCode: false

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11

            - name: Load native binaries
              uses: ./.github/actions/load-native-binaries

            - name: Build rust plugin
              uses: gradle/gradle-build-action@v1
              with:
                  arguments: ":plugin:buildPlugin"

            - name: Save artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: intellij-rust
                  path: plugin/build/distributions/*.zip
