name: get rust versions
on:
    workflow_call:
        outputs:
            stable-version:
                value: ${{ jobs.get_versions.outputs.stable-version}}
            nightly-version:
                value: ${{ jobs.get_versions.outputs.nightly-version}}
    workflow_dispatch:

jobs:
    get_versions:
        runs-on: ubuntu-latest
        outputs:
            stable-version: ${{ steps.stable.outputs.stable-version}}
            nightly-version: ${{ steps.nightly.outputs.nightly-version}}
        steps:
              - name: stable version
                id: stable
                run: echo "stable-version=1.64.0" >> $GITHUB_OUTPUT
              - name: nightly version
                id: nightly
                run: echo "nightly-version=nightly-2022-08-27" >> $GITHUB_OUTPUT
