# This workflow exist only to avoid using hardcoded versions of the toolchain in different files.
# In an ideal world, top level constants (not yet invented) or workflow level environment variables
#    would be used, but these are not supported in all needed places.


name: get rust versions
on:
    workflow_call:
        outputs:
            stable-version:
                value: ${{ jobs.get_versions.outputs.stable-version}}
            nightly-version:
                value: ${{ jobs.get_versions.outputs.nightly-version}}
            matrix-version:
                value: ${{ jobs.get_versions.outputs.matrix-version}}


jobs:
    get_versions:
        runs-on: ubuntu-latest
        outputs:
            stable-version: ${{ steps.stable.outputs.stable-version}}
            nightly-version: ${{ steps.nightly.outputs.nightly-version}}
            matrix-version: ${{ steps.matrix.outputs.matrix-version}}
        steps:
              - name: stable version
                id: stable
                run: echo "stable-version=1.64.0" >> $GITHUB_OUTPUT
              - name: nightly version
                id: nightly
                run: echo "nightly-version=nightly-2022-08-27" >> $GITHUB_OUTPUT
              - name: matrix version
                id: matrix
#                run: echo "matrix-version=[${{steps.stable.outputs.stable-version}}, ${{steps.nightly.outputs.nightly-version}}]" >> $GITHUB_OUTPUT //  Unexpected type of value '[1.64.0, nightly-2022-08-27]', expected type: Sequence.
                run: echo "matrix-version=["1.64.0", "nightly-2022-08-27"]" >> $GITHUB_OUTPUT
