name: Notify users based on labels
on:
  issues:
      types: [labeled]
  pull_request:
      types: [labeled]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: bugobliterator/issue-label-notification-action@pr-pr-notify
          with:
             recipients: |
                  help wanted=@neonaot
                  documentation=@neonaot
             message: |
                  help wanted='{receipients} look here, there is label {label}!'
                  documentation='documentation! {receipients} look here'
