name: notifier for docteam

on:
    pull_request_target:
        types: [ labeled, closed ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo content
              uses: actions/checkout@v2

            - name: Setup python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Install python packages 2
              run: pip install PyGithub

            - name: Execute py script
              run: python scripts/with_pygithub/notifier.py --token ${{ secrets.WORKFLOW_GITHUB_TOKEN }} --event ${{ github.event.action }} --pull_request ${{ github.event.pull_request.number }} --label "${{ github.event.label.name }}" --repo ${{ github.repository }}
