name: regressions

on: [ workflow_dispatch, pull_request ]

# Allow cancelling all previous runs for the same branch
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    calculate-base-commit:
        runs-on: ubuntu-18.04
        outputs:
            base-commit: ${{ steps.base-commit.outputs.base-commit }}
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            # In case of `workflow_dispatch` event, `github.sha` points to latest commit of chosen branch
            # So, we need to find the latest common commit for master branch and chosen one
            # to calculate difference only for branch changes
            - name: Calculate base commit for workflow_dispatch event
              if: github.event_name == 'workflow_dispatch'
              run: echo "BASE_COMMIT=$(git merge-base origin/master ${{ github.sha }})" >> $GITHUB_ENV

            # For pull request event, GitHub produces additional merge commit with `master` branch and PR branch as parents
            # In this case, we want to check difference between master branch and merge commit
            # so emit hash of `origin/master` branch itself as base commit
            - name: Calculate base commit for pull_request event
              if: github.event_name == 'pull_request'
              run: echo "BASE_COMMIT=$(git rev-parse origin/master)" >> $GITHUB_ENV

            - name: Emit base commit
              id: base-commit
              run: echo "::set-output name=base-commit::$BASE_COMMIT"

            - name: Show commits
              run: |
                  echo "current commit:"
                  git log ${{ github.sha }} -n 1 --pretty=short
                  echo "base commit:"
                  git log ${{ steps.base-commit.outputs.base-commit }} -n 1 --pretty=short

    check:
        needs: [ calculate-base-commit ]
        name: ${{ matrix.batch.name }}
        runs-on: ubuntu-18.04
        strategy:
            fail-fast: false
            matrix:
                batch:
                    - name: regressions-1
                      projects:
                          - name: cargo
                            repository: rust-lang/cargo
                          - name: tokio
                            repository: tokio-rs/tokio
                          - name: amethyst
                            repository: amethyst/amethyst
                    - name: regressions-2
                      projects:
                          - name: stdlib
        env:
            ORG_GRADLE_PROJECT_showStandardStreams: true
            PROJECTS: ${{ toJSON(matrix.batch.projects) }}
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11

            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7

            - name: Set up Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  components: rust-src
                  default: true

            - name: Install amethyst dependencies
              run: sudo apt-get install -y libasound2-dev

            - name: Checkout projects
              run: python scripts/fetch_projects.py --projects $'${{ toJSON(matrix.batch.projects) }}'

            - name: Download
              uses: gradle/gradle-build-action@v1
              with:
                  arguments: ":resolveDependencies -Pkotlin.incremental=false"

            - name: Check with changes
              uses: gradle/gradle-build-action@v1
              env:
                  RESULT_SUFFIX: _with_changes
              with:
                  arguments: "clean :test --tests \"org.rustPerformanceTests.CustomRealProjectAnalysisTest\""

            - name: Checkout base version
              run: git checkout ${{ needs.calculate-base-commit.outputs.base-commit }}

            - name: Check without changes
              uses: gradle/gradle-build-action@v1
              env:
                  RESULT_SUFFIX: _without_changes
              with:
                  arguments: "clean :test --tests \"org.rustPerformanceTests.CustomRealProjectAnalysisTest\""

            - name: Checkout current version
              run: git checkout ${{ github.sha }}

            - name: Calculate regressions
              run: python scripts/calculate_regressions.py --projects $'${{ toJSON(matrix.batch.projects) }}'

            - name: Upload results
              if: ${{ always() }}
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.batch.name }}
                  path: regressions/
