name: supported errors

on:
    schedule:
        - cron: '15 * * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo content
              uses: actions/checkout@v2

            - name: Setup python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Install pygithub
              run: pip install PyGithub

            - name: Install BeautifulSoup
              run: pip install bs4

            - name: Install urllib
              run: pip install urllib

            - name: Execute py script
              run: python scripts/with_pygithub/check_tracking_issue.py --token ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
                 --repo ${{ github.repository }}
